name: Sum
options:
  bundleIdPrefix: org.sum
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"

targets:
  Sum:
    type: application
    platform: iOS
    sources:
      - path: Sum/Sources
        type: group
      - path: Sum/Resources
        type: group
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.sum.calculator
        INFOPLIST_GENERATION_MODE: GeneratedByXcode
        MARKETING_VERSION: "1.3.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: 3V55494FNM
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleDisplayName: "Sum"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: YES
        TARGETED_DEVICE_FAMILY: "1,2"
  SumTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SumTests
        type: group
    dependencies:
      - target: Sum
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.sum.calculator.tests
        GENERATE_INFOPLIST_FILE: YES
        DEVELOPMENT_TEAM: 3V55494FNM
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
